print()
print()
print("10:44 - You: Hello server!")
print("10:44 - Server: Hello client!")
print("10:47 - Client: How are you?")
print("10:47 - Server: Everyhting is good! Thanks!")
print("10:48 - Client: Do you love C#?")
print("10:48 - Server: Yes of course!")
print()
print()
